### ISSUE TITLE
Failed on ['1a0q'] CUDA out of memory

### ISSUE THREAD

**Issue by amir-tagh** [gcorso/DiffDock#127]
Hello,

I am using a bash script running the diffdock comparing the results with autodock gpu but I am getting the following error, can you please let me know how I can solve this.

Thanks,
Amir

error
--------------------------------------------------------
Generating ESM language model embeddings
Processing 1 of 1 batches (2 sequences)
HAPPENING | confidence model uses different type of graphs than the score model. Loading (or creating if not existing) the data for the confidence model now.
Size of test dataset:  1
1it [00:03,  3.94s/it]
Failed on ['1a0q'] CUDA out of memory. Tried to allocate 5.44 GiB (GPU 0; 10.76 GiB total capacity; 1.31 GiB already allocated; 4.70 GiB free; 5.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Failed for 1 complexes
Skipped 0 complexes

#!/bin/bash

#SBATCH --job-name=dock1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=error.out
#SBATCH --account=scripps-dept
#SBATCH --qos=scripps-dept
#SBATCH --mem=50G
#SBATCH --time=7:00:00

python -m inference --protein_path protein.pdb --ligand "NC(=O)CNC(=O)[C@@H]1CCCCN1C(=O)c1ccc2nc(-c3c[nH]c4ncccc34)[nH]c2c1"

**Comment by ilkwonch** [comment]
The problem is associated with your CUDA memory. you should add --batch_size option and then decrease the batch size to handle this error. ( ex) --batch_size 8 )

**Comment by amir-tagh** [comment]
Thank you, setting the --batch_size to 6 solved my problem.
